[tools]
gh = "latest"
go = "1.22"
gomigrate = "4.18.1"
helm = "3.16.3"
kind = "0.25.0"
kubectl = "1.29.11"
node = "20.10.0"
"pipx:commitizen" = "4.4.1"
"pipx:pre-commit" = "4.1.0"
"pipx:yamllint" = "1.36.0"
sops = "3.9.2"
terraform = "1.10.1"

[hooks]
enter = "mise i -q"
