apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gofit
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: gofit=docker.io/bamaas/gofit:latest
    argocd-image-updater.argoproj.io/gofit.update-strategy: digest
    argocd-image-updater.argoproj.io/write-back-method: argocd
    argocd-image-updater.argoproj.io/gofit.force-update: "true"
    argocd-image-updater.argoproj.io/gofit.helm.image-name: image.repository
    argocd-image-updater.argoproj.io/gofit.helm.image-tag: image.tag
spec:
  destination:
    name: ''
    namespace: gofit
    server: 'https://kubernetes.default.svc'
  sources:
    - path: deploy/chart/gofit
      repoURL: 'https://github.com/bamaas/gofit'
      targetRevision: HEAD
      helm:
        valueFiles:
          - ../../../deploy/homelab/values.yaml
          - secrets://../../../deploy/homelab/secret.values.enc.yaml
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
