users:
    - email: ENC[AES256_GCM,data:eRgMpgnaf/y7tZTh5A==,iv:H0MlHHr7DdW2WhKO0TGHVk/FcRNcD2h9dE+XrusHF2o=,tag:FadAMTwzbTWlq2/A9ZdMUw==,type:str]
      password: ENC[AES256_GCM,data:3i6mvGUACmc=,iv:GmuvXQrynXG0LnT0MGbE39dstlFhiJobu7ec9M1zsA0=,tag:ui9yLouTQZuGHeoYyjViOQ==,type:str]
    - email: ENC[AES256_GCM,data:PXXMzgENyi/gzN0B7+6OU0wxNKQ=,iv:Geh7dgzDWs/tIGIGpm5QwrLk0QSKSu/tHZ2biM27TCU=,tag:IwIwkr2sbZVIJLzw04Wx3Q==,type:str]
      password: ENC[AES256_GCM,data:HiRHl/8QHcwLi3RH,iv:zXfs9sukF//o5rTfdX5bL5deZ17J+7ZWIFtQWY0BcDA=,tag:+hjDnIxC7dy9SwRBwmiD9w==,type:str]
    - email: ENC[AES256_GCM,data:NK+EsqiKKKtiQ3esFA==,iv:BlAaK8QanckS2zxNQgyBREaaLBA90aGs1YWPCwvOYIM=,tag:XO5U1cl5r24jY0tS++fIHg==,type:str]
      password: ENC[AES256_GCM,data:e6qW+rhn6imHtxk=,iv:yfEV7S3ac/GaTYqfDu9lK6GZWLZppbkBZKf6hw2zBWs=,tag:c+nOZvVLlcw6WV5en/fXEQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv:
        - vault_url: https://sops-3caeb0533c5a473f.vault.azure.net
          name: sops-key
          version: b2031a08aea14a50ab6d8e72548eb4f9
          created_at: "2024-07-14T17:03:50Z"
          enc: PBuKO2NAJdT-bJVKvnTxo94MLLqpLYo26ncPH-wZ7W-gYJIz0mZPqE9twf2bthsPbGsb4ySvAsASXbz8ATQwhvj14Pxy8lHdQXYrLuD3ni26Wc3h7TLDPZDmETH5EKYrahF_198LsVck8rzcWqXZ1o5vi1vXb6fCbjp9zIklzXaR8_5XCuBKBhjH5HC5Ek4eLTrj24FTKTrCcsn09nf75ZKBtyOY34Ko-_miAcsR4PbWuw5R0fnz-h7LeqIc3Kopz5xd4hAXPu0sPKg0lv-EcyylZ_mlyIGoQZVlMK5ZhYNV2CEYqREf3luFZm09fvtMetKdz6SQOezte-v2zuAWLw
    hc_vault: []
    age: []
    lastmodified: "2024-07-14T17:03:51Z"
    mac: ENC[AES256_GCM,data:SIJvgppegmpvtyYKRn14B4wOP3KQ4BIHngqb+MKzbprJp0wChB5nlqxHd3+FiH6oBUusU2Qb4WQSpaDmvtRj8kw9K1T6Ur7j7p8RbQkdsCBKUbWjMxgtYZIL0PxwwDwE+NmhEM0U3dEatWFoLX6mVLUK8BDnh1n/c7ml7yMq178=,iv:jfNxn4rAKID4xIaL11tx/DN99+UUR6KsO26/ynrE9xg=,tag:K0UWs8AEJpYEhg2qtoC1lQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
