image:
  name: bamaas/gofit
  pullPolicy: IfNotPresent
  tag: "0.0.1"

ingress:
  enabled: true
  annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prd
  hosts:
    - host: gofit.kubernetes.lan.basmaas.nl
      paths:
        - path: /
          pathType: Prefix
          port: 8080
  tls:
    - secretName: gofit.kubernetes.lan.basmaas.nl
      hosts:
        - gofit.kubernetes.lan.basmaas.nl

podSecurityContext:
  fsGroup: 1001
  fsGroupChangePolicy: Always
  runAsGroup: 1001
  runAsNonRoot: true
  runAsUser: 1001