apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gofit.fullname" . }}
  labels:
    {{- include "gofit.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gofit.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gofit.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: {{ include "gofit.fullname" . }}
        - secretRef:
            name: {{ include "gofit.fullname" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}
        resources: {}
        {{- if .Values.persistence.enabled }}
        volumeMounts:
          - name: data
            mountPath: /data
        {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "gofit.fullname" . }}
      {{- end }}
