{{- $fullName := include "gofit.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "gofit.fullname" . }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
  labels:
    {{- include "gofit.labels" . | nindent 4 }}
spec:
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
        {{- range .paths }}
        - path: {{ .path }}
          pathType: {{ .pathType }}
          backend:
            service:
              name: {{ $fullName }}
              port:
                number: {{ .port }}
        {{- end }}
    {{- end }}
