apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gofit.fullname" . }}
  labels:
    {{- include "gofit.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.storage }}
