apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "gofit.labels" . | nindent 4 }}
  name: {{ include "gofit.fullname" . }}
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
      {{- include "gofit.labels" . | nindent 4 }}
      {{- with .Values.podLabels }}
      {{- toYaml . | nindent 4 }}
      {{- end }}
  type: {{ .Values.service.type }}
