---

trigger:
  - "*"

pool:
  vmImage: ubuntu-latest

container: 
  image: docker.io/bamaas/devcontainer:10f749ea9e0c7a4bc9dc1663f00cf98ceabfaa34
  options: --entrypoint ""

steps:

  - task: Docker@2
    displayName: Login to DockerHub
    inputs:
      command: login
      containerRegistry: dockerhub

  - script: make image/build
    displayName: Build image
    env:
      IMAGE_TAG: $(Build.SourceVersion)

  - ${{ if eq( variables['Build.SourceBranch'], 'refs/heads/main' ) }}:
      - script: make image/retag-to-latest
        displayName: Retag image to latest
        env:
          IMAGE_TAG: $(Build.SourceVersion)

      - script: make image/push
        displayName: Push image with tag $(Build.SourceVersion)
        env:
          IMAGE_TAG: $(Build.SourceVersion)

      - script: make image/push
        displayName: Push image with latest tag
        env:
          IMAGE_TAG: latest

      - script: |
          echo "##vso[task.setvariable variable=image]$(make image/get)"
          echo "Defined backend image task variable value: ${image}"
        displayName: Define image task variable
        env:
          IMAGE_TAG: $(Build.SourceVersion)

      - task: AzureWebAppContainer@1
        displayName: Deploy backend
        inputs:
          azureSubscription: gofit-ARM
          appName: gofit-api
          containers: $(image)

      # TODO: fix this
      # - script: |
      #     # TODO: set PUBLIC_BACKEND_BASE_URL="https://gofit-api.azurewebsites.net/api" in ./frontend/.env.production
      #   displayName: Build frontend

      - task: AzureStaticWebApp@0
        displayName: Deploy frontend
        inputs:
          app_location: '/frontend'
          output_location: '/build'
          azure_static_web_apps_api_token: $(DEPLOYMENT_TOKEN)
          production_branch: main
