---

trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:

  - task: Docker@2
    displayName: Login to DockerHub
    inputs:
      command: login
      containerRegistry: dockerhub

  - script: make image/build
    displayName: Build image
    env:
      IMAGE_TAG: $(Build.SourceVersion)

  - script: make image/push
    displayName: Push image
    env:
      IMAGE_TAG: $(Build.SourceVersion)

  - script: |
      echo "##vso[task.setvariable variable=image]$(make image/get)"
      echo "Defined backend image task variable value: ${image}"
    displayName: Define image task variable
    env:
      IMAGE_TAG: $(Build.SourceVersion)

  - task: AzureWebAppContainer@1
    displayName: Deploy backend
    inputs:
      azureSubscription: gofit-ARM
      appName: gofit-api
      containers: $(image)

  - task: AzureStaticWebApp@0
    displayName: Deploy frontend
    inputs:
      app_location: '/frontend'
      output_location: '/build'
      azure_static_web_apps_api_token: $(DEPLOYMENT_TOKEN)
      production_branch: main