users: []
  # - email: "user@gofit.nl"
  #   password: "gofit123"

logLevel: info

replicaCount: 1

image:
  repository: bamaas/gofit
  pullPolicy: IfNotPresent
  tag: "6f2494c151a144abb02d5d12aa271487ff132ae4"

podLabels: {}

persistence:
  enabled: false
  size: 10Mi
  accessModes: 
    - ReadWriteOnce
  storageClass: ""

ingress:
  enabled: false
  annotations: {}
  hosts: []
    # - host: gofit.kubernetes.lan.basmaas.nl
    #   paths:
    #     - path: /
    #       pathType: Prefix
    #       port: 8080
  tls: []
    # - secretName: gofit.kubernetes.lan.basmaas.nl
    #   hosts:
    #     - gofit.kubernetes.lan.basmaas.nl

service:
  type: ClusterIP
  port: 8080

podSecurityContext:
  fsGroup: 1001
  fsGroupChangePolicy: Always
  runAsGroup: 1001
  runAsNonRoot: true
  runAsUser: 1001