---
users: []
  # - email: "user@gofit.nl"
  #   password: "gofit123"

logLevel: info

replicaCount: 1

image:
  registry: ghcr.io
  repository: bamaas/gofit
  pullPolicy: IfNotPresent
  tag: "0.0.1"

podLabels: {}

persistence:
  enabled: false
  size: 10Mi
  accessModes:
    - ReadWriteOnce
  storageClass: ""

ingress:
  enabled: false
  annotations: {}
  hosts: []
    # - host: gofit.kubernetes.lan.basmaas.nl
    #   paths:
    #     - path: /
    #       pathType: Prefix
    #       port: 8080
  tls: []
    # - secretName: gofit.kubernetes.lan.basmaas.nl
    #   hosts:
    #     - gofit.kubernetes.lan.basmaas.nl

service:
  type: ClusterIP
  port: 8080

podSecurityContext: {}
